import React from "react";
import { createRoot } from "react-dom/client";
import { AuthProvider, LoginScreen, useAuth } from "./auth/Auth";
import { useCrm } from "./lib/useCrm";
import "./styles.css";

function App() {
  const { user, logout } = useAuth();
  const { leads, selected, setSelected, timeline, loading } = useCrm();
  const active = selected ?? leads[0];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><strong>Shvya AI</strong><span>CRM</span></div></div><nav>{["Dashboard","Leads","Contacts","Pipeline","Inbox","WhatsApp","AI Agents","Automations","Calls","Calendar","Integrations","Reports"].map((item, index) => <button className={index === 0 ? "nav-item active" : "nav-item"} key={item}><span className="nav-dot" />{item}</button>)}</nav><div className="sidebar-footer">{user?.organizationId?.slice(0, 8)} · <button className="link-button" onClick={logout}>Sign out</button></div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Sales workspace</div><h1>Good morning, {user?.name ?? "there"}</h1></div><div className="top-actions"><button className="icon-button">⌕</button><button className="icon-button">◔</button><div className="avatar">{(user?.name ?? "DY").slice(0, 2).toUpperCase()}</div></div></header><section className="stats-grid"><Stat label="Total leads" value={String(leads.length)} delta="Live from CRM" /><Stat label="Qualified" value={String(leads.filter(x => x.stage === "qualified").length)} delta="Current pipeline" /><Stat label="Follow-ups due" value="—" delta="Automation coming next" /><Stat label="High intent" value={String(leads.filter(x => x.score >= 80).length)} delta="Score ≥ 80" /></section><section className="content-grid"><div className="panel"><div className="panel-header"><div><h2>Recent leads</h2><span>{loading ? "Loading CRM…" : "Live sales workspace"}</span></div></div><div className="lead-list">{leads.map(lead => <button className={`lead-row ${active?.id === lead.id ? "selected" : ""}`} key={lead.id} onClick={() => setSelected(lead)}><div className="lead-avatar">{lead.name.slice(0, 2).toUpperCase()}</div><div className="lead-main"><strong>{lead.name}</strong><span>{lead.company ?? "No company"} · {lead.source}</span></div><div className="lead-status"><span className="pill">{lead.stage}</span><small>{lead.status}</small></div><div className="score">{lead.score}</div></button>)}{!loading && !leads.length && <div className="empty-caller"><p>No leads yet. Create your first lead through the API.</p></div>}</div></div><CallerPanel lead={active} timeline={timeline} /></section></main></div>;
}

function Stat({ label, value, delta }: { label: string; value: string; delta: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{delta}</small></div>; }

function CallerPanel({ lead, timeline }: { lead?: any; timeline: any[] }) { return <div className="panel caller-panel"><div className="call-banner"><span className="live-dot" /> Customer context</div>{lead ? <><div className="caller-head"><div className="caller-avatar">{lead.name.slice(0, 2).toUpperCase()}</div><div><strong>{lead.name}</strong><span>{lead.phone ?? "No phone"}</span></div><span className="existing">Existing lead</span></div><div className="caller-meta"><div><span>Stage</span><strong>{lead.stage}</strong></div><div><span>Lead score</span><strong>{lead.score}/100</strong></div><div><span>Last activity</span><strong>{timeline[0] ? formatAge(timeline[0].occurredAt) : "No activity"}</strong></div></div><div className="ai-brief"><div className="ai-title">✦ AI context</div><p>{timeline[0]?.body ?? "No recent conversation yet. AI brief will appear after connected channels send activity."}</p></div><div className="timeline-mini"><div className="timeline-title">Recent conversation</div>{timeline.slice(0, 5).map(item => <div className="timeline-item" key={item.id}><span className={`channel ${item.type}`}>{item.type.slice(0, 1).toUpperCase()}</span><div><strong>{item.type}</strong><span>{item.body ?? "Activity recorded"}</span></div><small>{formatAge(item.occurredAt)}</small></div>)}{!timeline.length && <span className="muted">No activity yet</span>}</div><div className="caller-actions"><button className="primary-button">Open CRM</button><button className="secondary-button">Open WhatsApp</button><button className="secondary-button">Add note</button></div></> : <div className="empty-caller"><p>Select a lead to see its live timeline and caller context.</p></div>}</div>; }

function formatAge(value?: string) { if (!value) return "No activity"; const hours = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 3600000)); return hours < 24 ? `${hours}h ago` : `${Math.round(hours / 24)}d ago`; }

function Root() { const { user, loading } = useAuth(); if (loading) return <div className="auth-screen"><div className="auth-card">Loading Shvya AI…</div></div>; return user ? <App /> : <LoginScreen />; }

createRoot(document.getElementById("root")!).render(<React.StrictMode><AuthProvider><Root /></AuthProvider></React.StrictMode>);
